/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.form;

import java.awt.BorderLayout;
import javax.swing.ImageIcon;

/**
 *
 * @author baptista
 */
public class PanelMain extends javax.swing.JPanel {

    /**
     * Creates new form Main
     */
    public PanelMain(ImageIcon ico, String nome) {
        initComponents();
        com.swing.custom.components.ImageAvatar icon = new com.swing.custom.components.ImageAvatar();
        icon.setImage(ico);
        lblNome.setText(nome);
        this.add(icon, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();

        setBackground(new java.awt.Color(254, 254, 254));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(621, 60));
        jPanel1.setLayout(new java.awt.BorderLayout());

        lblTitle.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(56, 187, 240));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("SISTEMA DE ATENDIMENTO AO PÚBLICO");
        lblTitle.setPreferredSize(new java.awt.Dimension(243, 79));
        jPanel1.add(lblTitle, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(621, 70));
        jPanel2.setLayout(new java.awt.BorderLayout());

        lblNome.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblNome.setForeground(new java.awt.Color(56, 187, 240));
        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNome.setText("TELA INICIAL");
        lblNome.setPreferredSize(new java.awt.Dimension(243, 79));
        jPanel2.add(lblNome, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
