/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.form;

import com.controller.ControllerUsuario;
import com.model.ModelUser;
import com.form.Main;
import datechooser.Button;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import message.MessageDialog;

/**
 *
 * @author baptista
 */
public class PanelProcurar extends javax.swing.JPanel {

    private final Main frame;
    private DefaultTableModel defaultModel;

    /**
     * Creates new form PanelSearch
     */
    public PanelProcurar(Main frame) {
        initComponents();
        this.frame = frame;
        init();

    }

    private void init() {
        
        table1.getParent().setBackground(Color.WHITE);
        defaultModel = new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "ID", "Nome", "B.I"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textField1 = new com.swing.custom.components.TextField();
        lbIcon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnACaixa = new Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new com.swing.custom.components.Table();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(646, 60));
        jPanel1.setLayout(new java.awt.BorderLayout());

        textField1.setLabelText("Nome do funcionário");
        textField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textField1KeyReleased(evt);
            }
        });
        jPanel1.add(textField1, java.awt.BorderLayout.CENTER);
        jPanel1.add(lbIcon, java.awt.BorderLayout.LINE_END);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 40, 10);
        flowLayout1.setAlignOnBaseline(true);
        jPanel2.setLayout(flowLayout1);

        btnACaixa.setBackground(new java.awt.Color(25, 182, 247));
        btnACaixa.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        btnACaixa.setForeground(new java.awt.Color(255, 255, 255));
        btnACaixa.setText("Ver dados");
        btnACaixa.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnACaixa.setOpaque(true);
        btnACaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnACaixaActionPerformed(evt);
            }
        });
        jPanel2.add(btnACaixa);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        table1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null}
                },
                new String[]{
                    "ID", "Nome", "B.I"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane1.setViewportView(table1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>                        

    private void verDados() {

        int row = table1.getSelectedRow();
        if (row < 0) {
            message.MessageDialog message = new MessageDialog(frame, MessageDialog.Type.INFO);
            message.showMessage("Aviso", "Selecione um funcionário da tabela");
            return;
        }
        int id = Integer.parseInt(table1.getModel().getValueAt(row, 0).toString());
        ModelUser us = new ControllerUsuario().getUser(frame, id);
        if (us == null) {
            message.MessageDialog message = new MessageDialog(frame, MessageDialog.Type.INFO);
            message.showMessage("Aviso", "Houve um erro ao buscar todos os dados do funcionário! Tente novamente");
        } else {
            frame.showForm(new PanelUsuario(frame, us, 0));
        }
    }

    private void btnACaixaActionPerformed(java.awt.event.ActionEvent evt) {
        setCursor(new Cursor(Cursor.WAIT_CURSOR));
        verDados();
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }

    private void textField1KeyReleased(java.awt.event.KeyEvent evt) {

        String text = textField1.getText();

        if (text.isEmpty()) {
            table1.setModel(defaultModel);
        } else {
            TableModel model = new ControllerUsuario().getUser(frame, text);
            table1.setModel(model);
        }
    }

    // Variables declaration - do not modify                     
    private Button btnACaixa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbIcon;
    private com.swing.custom.components.Table table1;
    private com.swing.custom.components.TextField textField1;
    // End of variables declaration                   
}
